### PR TITLE
Occluderexample

### PR DESCRIPTION
**Pull request by davidejones**
Occluder example. 

The only thing I could think of that this could be useful for using the occluder class would be for a scene where outside a building you do not want to render the contents of the inside of a building.

My example shows a house with 58 triangles inside the house is an occluder and inside occluder is a monkey mesh of around 1000 triangles.

As camera zooms into house and through the occluder you can see the triangle count change.

### CODE REVIEW

**Comment by makc** [comment]
you could probably do the same with LOD but nice idea )

**Comment by davidejones** [comment]
Thanks, I was trying to make something that might be useful. I couldn't think of how else you can really use the occluder.

**Comment by pecheny** [comment]
> The only thing I could think of that this could be useful for using the occluder class would be for a scene where outside a > building you do not want to render the contents of the inside of a building.

This is not exactly right. In real occluder disable render not only for objects which placed _inside_ but also objects _behind_. It can be very useful in game where you walk in corridors and a lot of geometry placed behind walls or so.
You can look at example of occluder usage in Alternativa3D 7 [here](http://wiki.alternativaplatform.com/%D0%9E%D0%BA%D0%BA%D0%BB%D1%8E%D0%B4%D0%B5%D1%80).
(Move left or right to see what happens)
It will be great if you can extend your example according to such cases of use.

**Comment by makc** [comment]
that assumes this geometry is all in separate meshes, right? if all the walls are one giant terrain-like mesh, this will not help.

**Comment by pecheny** [comment]
Correct. But this approach is not perfect. Culling by camera's frustum will also unavailable.

**Comment by makc** [comment]
so you are saying, 1000 small drawcalls with 500 culled is better than 1 bigass drawcall?

**Comment by pecheny** [comment]
It depends. If your scene is small so you're right – one big drawcal is better. But in cases of big scene – this scene can't fit into one drawcall anyway. Thus it is bad to split meshes by each ten triangles, but as for mesh of 1M tri – it is better to split it on smaller ones.

**Comment by makc** [comment]
Ooooh, @davidejones got mad that his PRs were not accepted for almost 8 years? You still have AlternativaTools repo pinned in your profile, how nice :) What are you up to these days? I hack [multiplayer mode into games](https://github.com/makc/Edelweiss) for fun. What about you, @pecheny?

**Comment by davidejones** [comment]
> 
> 
> Ooooh, @davidejones got mad that his PRs were not accepted for almost 8 years? You still have AlternativaTools repo pinned in your profile, how nice :) What are you up to these days? I hack [multiplayer mode into games](https://github.com/makc/Edelweiss) for fun. What about you, @pecheny?

Hey @makc! Haha so mad 😠 but really I just discovered that https://github.com/pulls lists all your PRs in github across projects and saw all my old Alternativa PRs and thought I'd close them down. 

Nice multiplayer mod! I mostly do Frontend / Backend website work these days sometimes I'll dabble and make some game clones in my spare time but nothing crazy. Ever since the days i played with alternativa I have a strong urge to be doing more of the same though it was fun to work on.

Are you mostly doing webgl / three.js?

**Pull request closed without merging**
